"""Add dry_run to subscriptions and create order_logs table

Revision ID: 1d197469eec1
Revises: 005
Create Date: 2026-01-23 20:54:36.513343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d197469eec1'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_subscriptions', sa.Column('dry_run', sa.Boolean(), nullable=True))

    # Set default value for existing records
    op.execute("UPDATE strategy_subscriptions SET dry_run = false WHERE dry_run IS NULL")

    # Make column non-nullable with default
    op.alter_column('strategy_subscriptions', 'dry_run', nullable=False, server_default='false')

    # Create order_logs table
    op.create_table(
        'order_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('subscription_id', sa.UUID(), nullable=True),  # Nullable for test orders
        sa.Column('order_id', sa.UUID(), nullable=True),
        sa.Column('symbol', sa.String(50), nullable=False),
        sa.Column('exchange', sa.String(20), nullable=False),
        sa.Column('order_type', sa.String(20), nullable=False),
        sa.Column('transaction_type', sa.String(10), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('price', sa.Numeric(15, 4), nullable=True),
        sa.Column('trigger_price', sa.Numeric(15, 4), nullable=True),
        sa.Column('event_type', sa.String(30), nullable=False),
        sa.Column('is_dry_run', sa.Boolean(), nullable=True),
        sa.Column('is_test_order', sa.Boolean(), nullable=True),
        sa.Column('success', sa.Boolean(), nullable=True),
        sa.Column('broker_order_id', sa.String(100), nullable=True),
        sa.Column('broker_name', sa.String(50), nullable=True),
        sa.Column('broker_request', sa.dialects.postgresql.JSONB(), nullable=True),
        sa.Column('broker_response', sa.dialects.postgresql.JSONB(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('strategy_name', sa.String(100), nullable=True),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('market_price', sa.Numeric(15, 4), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['subscription_id'], ['strategy_subscriptions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_logs_subscription_id'), 'order_logs', ['subscription_id'])
    op.create_index(op.f('ix_order_logs_event_type'), 'order_logs', ['event_type'])
    op.create_index(op.f('ix_order_logs_is_dry_run'), 'order_logs', ['is_dry_run'])
    op.create_index(op.f('ix_order_logs_created_at'), 'order_logs', ['created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_logs_created_at'), 'order_logs')
    op.drop_index(op.f('ix_order_logs_is_dry_run'), 'order_logs')
    op.drop_index(op.f('ix_order_logs_event_type'), 'order_logs')
    op.drop_index(op.f('ix_order_logs_subscription_id'), 'order_logs')
    op.drop_table('order_logs')
    op.drop_column('strategy_subscriptions', 'dry_run')
    # ### end Alembic commands ###
